// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameAnggotum = "anggota"

// Anggotum mapped from table <anggota>
type Anggotum struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Kta    string `gorm:"column:kta" json:"kta"`
	Nama   string `gorm:"column:nama" json:"nama"`
	Status string `gorm:"column:status" json:"status"`
}

// TableName Anggotum's table name
func (*Anggotum) TableName() string {
	return TableNameAnggotum
}
