// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameCabang = "cabang"

// Cabang mapped from table <cabang>
type Cabang struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NamaCabang   string `gorm:"column:nama_cabang" json:"nama_cabang"`
	AlamatKantor string `gorm:"column:alamat_kantor" json:"alamat_kantor"`
	DaerahID     int64  `gorm:"column:daerah_id" json:"daerah_id"`
}

// TableName Cabang's table name
func (*Cabang) TableName() string {
	return TableNameCabang
}
