// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameInfoAnggotum = "info_anggota"

// InfoAnggotum mapped from table <info_anggota>
type InfoAnggotum struct {
	ID                     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Profesi                string `gorm:"column:profesi" json:"profesi"`
	ProfesiLainnya         string `gorm:"column:profesi_lainnya" json:"profesi_lainnya"`
	Pekerjaan              string `gorm:"column:pekerjaan" json:"pekerjaan"`
	Instansi               string `gorm:"column:instansi" json:"instansi"`
	PendidikanTerakhir     string `gorm:"column:pendidikan_terakhir" json:"pendidikan_terakhir"`
	PernahBelajarPesantren bool   `gorm:"column:pernah_belajar_pesantren" json:"pernah_belajar_pesantren"`
	Bahasa                 string `gorm:"column:bahasa" json:"bahasa"`
	Organisasi             string `gorm:"column:organisasi" json:"organisasi"`
}

// TableName InfoAnggotum's table name
func (*InfoAnggotum) TableName() string {
	return TableNameInfoAnggotum
}
