// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNamePengajuan = "pengajuan"

// Pengajuan mapped from table <pengajuan>
type Pengajuan struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AsalKantorID    int64  `gorm:"column:asal_kantor_id;not null" json:"asal_kantor_id"`
	TujuanKantorID  int64  `gorm:"column:tujuan_kantor_id;not null" json:"tujuan_kantor_id"`
	StatusPengajuan string `gorm:"column:status_pengajuan" json:"status_pengajuan"`
	Keterangan      string `gorm:"column:keterangan" json:"keterangan"`
	File            string `gorm:"column:file" json:"file"`
}

// TableName Pengajuan's table name
func (*Pengajuan) TableName() string {
	return TableNamePengajuan
}
