// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNamePenguru = "pengurus"

// Penguru mapped from table <pengurus>
type Penguru struct {
	ID        int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AnggotaID int64 `gorm:"column:anggota_id" json:"anggota_id"`
	JabatanID int64 `gorm:"column:jabatan_id" json:"jabatan_id"`
}

// TableName Penguru's table name
func (*Penguru) TableName() string {
	return TableNamePenguru
}
