// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameRanting = "ranting"

// Ranting mapped from table <ranting>
type Ranting struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NamaRanting  string `gorm:"column:nama_ranting" json:"nama_ranting"`
	AlamatKantor string `gorm:"column:alamat_kantor" json:"alamat_kantor"`
	RantingID    int64  `gorm:"column:ranting_id" json:"ranting_id"`
	CabangID     int64  `gorm:"column:cabang_id" json:"cabang_id"`
}

// TableName Ranting's table name
func (*Ranting) TableName() string {
	return TableNameRanting
}
