// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

import (
	"time"
)

const TableNameRiwayatJabatan = "riwayat_jabatan"

// RiwayatJabatan mapped from table <riwayat_jabatan>
type RiwayatJabatan struct {
	ID                 int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PengurusID         int64     `gorm:"column:pengurus_id" json:"pengurus_id"`
	JabatanID          int64     `gorm:"column:jabatan_id" json:"jabatan_id"`
	TahunPengangkatan  time.Time `gorm:"column:tahun_pengangkatan" json:"tahun_pengangkatan"`
	TahunPemberhentian time.Time `gorm:"column:tahun_pemberhentian" json:"tahun_pemberhentian"`
}

// TableName RiwayatJabatan's table name
func (*RiwayatJabatan) TableName() string {
	return TableNameRiwayatJabatan
}
