// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Database

const TableNameWilayah = "wilayah"

// Wilayah mapped from table <wilayah>
type Wilayah struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NamaWilayah  string `gorm:"column:nama_wilayah" json:"nama_wilayah"`
	AlamatKantor int64  `gorm:"column:alamat_kantor" json:"alamat_kantor"`
}

// TableName Wilayah's table name
func (*Wilayah) TableName() string {
	return TableNameWilayah
}
