// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Route

import (
	"gorm.io/gorm"
	"muhammadiyah/Controller"
	"muhammadiyah/Repository"
	"muhammadiyah/Services"
)

// Injectors from wire.go:

func PWMDI(db *gorm.DB) *Controller.PWMControllerImpl {
	pwmRepositoryImpl := Repository.PWMRepositoryControllerProvider(db)
	pwmServiceImpl := Services.PWMServiceControllerProvider(pwmRepositoryImpl)
	pwmControllerImpl := Controller.PWMControllerControllerProvider(pwmServiceImpl)
	return pwmControllerImpl
}
